# General Configuration
version: 1.0.0.{build}
skip_branch_with_pr: true

# Environment Configuration
image: Visual Studio 2017
cache:
  - '%LocalAppData%\NuGet\v3-cache'

install:
  #init and update submodules
  - git submodule update --recursive --init
    # update node.js to latest 8.x release
  - ps: Install-Product node 8
  - node --version
  - npm --version

 # version
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'


# Build Configuration
platform: Any CPU
configuration: Release

environment:
  lastJob: 'Environment: solution_name=SpeckleRhino\SpeckleRhino.sln'
  matrix:
  - solution_name: SpeckleUpdater.sln
  - solution_name: SpeckleDynamo\SpeckleDynamo.sln
  - solution_name: SpeckleRhino\SpeckleRhino.sln

before_build:
  - nuget restore %solution_name%
  - ps: |
      if ($env:APPVEYOR_JOB_NAME -eq $env:lastJob) {
      mkdir %AppData%\Grasshopper\Libraries\SpeckleSendReceive
      mkdir Release
      cd SpeckleRhino\SpeckleView
      npm install
      npm run build
      cd ..\..
      }

build_script:
  - msbuild %solution_name%

build:
  project: $(solution_name)
  verbosity: minimal


# after_build:
#   - InnoSetup\ISCC.exe SpeckleInstaller.iss
after_build : 
  - ps: |
      if ($env:APPVEYOR_JOB_NAME -eq $env:lastJob) {
      InnoSetup\ISCC.exe SpeckleInstaller.iss
      }
      

artifacts:
  path: Speckle.exe
  name: Release

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#devtalk'
  template: Build <{{buildUrl}}|#{{buildVersion}}> (<{{commitUrl}}|{{commitId}}>) of {{repositoryName}}@{{branch}}) by {{commitAuthor}} {{status}} in {{duration}}
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
