# General Configuration
version: 1.0.0.{build}
skip_branch_with_pr: true

# Environment Configuration
image: Visual Studio 2017
cache:
  - '%LocalAppData%\NuGet\v3-cache'

 # version
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'


# Build Configuration
platform: Any CPU
configuration: Release

before_build:
  - nuget restore

build:
  project: SpeckleUpdater.sln
  verbosity: minimal


# after_build:
#   - InnoSetup\ISCC.exe SpeckleInstaller.iss
after_build : 
  - ps: |
      $apiUrl = 'https://ci.appveyor.com/api'
      $token = 'v2.bngo3nen438pm58fx2n1'
      $headers = @{
        "Authorization" = "Bearer $token"
        "Content-type" = "application/json"
      }
  # DOWNLOAD RHINO+GH ARTIFACTS
  - ps: |
      $prjUrl = "$apiUrl/projects/speckleworks/specklerhino/branch/master"
      $headers = @{
        "Authorization" = "Bearer $token"
        "Content-type" = "application/json"
      }
      $project = Invoke-RestMethod -Method Get -Uri "$prjUrl" -Headers $headers
      $jobId = $project.build.jobs[0].jobId
      $artifacts = Invoke-RestMethod -Method Get -Uri "$apiUrl/buildjobs/$jobId/artifacts" -Headers $headers
      $artifactFileName = $artifacts[0].fileName
      $localArtifactPath = "$Env:APPVEYOR_BUILD_FOLDER\$artifactFileName"
      Invoke-RestMethod -Method Get -Uri "$apiUrl/buildjobs/$jobId/artifacts/$artifactFileName" -OutFile $localArtifactPath -Headers $headers
      $dest = "$Env:APPVEYOR_BUILD_FOLDER\SpeckleRhino"
      7z x -o$dest $localArtifactPath -r -aoa
      Get-ChildItem $dest | 
      Foreach-Object {
          Write-Host Get-Content $_.FullName
      }
  # DOWNLOAD DYNAMO ARTIFACTS
  - ps: |
      $prjUrl = "$apiUrl/projects/speckleworks/speckledynamo/branch/master"
      $headers = @{
        "Authorization" = "Bearer $token"
        "Content-type" = "application/json"
      }
      $project = Invoke-RestMethod -Method Get -Uri "$prjUrl" -Headers $headers
      $jobId = $project.build.jobs[0].jobId
      $artifacts = Invoke-RestMethod -Method Get -Uri "$apiUrl/buildjobs/$jobId/artifacts" -Headers $headers
      $artifactFileName = $artifacts[0].fileName
      $localArtifactPath = "$Env:APPVEYOR_BUILD_FOLDER\$artifactFileName"
      Invoke-RestMethod -Method Get -Uri "$apiUrl/buildjobs/$jobId/artifacts/$artifactFileName" -OutFile $localArtifactPath -Headers $headers
      $dest = "$Env:APPVEYOR_BUILD_FOLDER\SpeckleDynamo"
      7z x -o$dest $localArtifactPath -r -aoa
            Get-ChildItem $dest | 
      Foreach-Object {
          Write-Host Get-Content $_.FullName
      }
  # EXECUTE INNO
  - InnoSetup\ISCC.exe SpeckleInstaller.iss

artifacts:
  path: Speckle.exe
  name: Release

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#devtalk'
  template: Build <{{buildUrl}}|#{{buildVersion}}> (<{{commitUrl}}|{{commitId}}>) of {{repositoryName}}@{{branch}}) by {{commitAuthor}} {{status}} in {{duration}}
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
